### ISSUE TITLE
Redesign Questionnaire Database structure

### ISSUE THREAD

**Issue by ketain** [TH-Brandenburg/University-Evaluation-Backend#1]
Currently questions are unique in the database. This is stupid on many levels.
-> Different Questionnaires share the same questions -> One cannot alter or delete another questionnaire without the risk to damage an unrelated one. This needs to be changed.

We did this because we never thought that 20 year old version would ever change... than came reality

**Comment by ColinChrist** [comment]
Da die DB mittels Hibernate erstellt wird, werden auch nur die Klassen die Hibernate verwendet geändert und nicht direkt die DB.

## Vorheriger Zustand

![hibernate_1](https://cloud.githubusercontent.com/assets/15246504/16912445/7d5d2b2c-4ce4-11e6-8f27-3e39a12cffd6.png)

## Geplante Änderungen

![newhibernate_2](https://cloud.githubusercontent.com/assets/15246504/17167438/7f3a74f4-53dd-11e6-818c-86f131b30a77.png)

## Erklärung
1. Question wurde zu TextQuestion. MC (Multi Choise) Klassen wurden korrekter weise zu SC (Single Choice) umbenannt.
2. TextQuestion und SCQuestion erben von Question. Dies ermöglicht, das es in Zukunft möglich ist andere Antworttypen leicht hinzuzufügen.
3. Evaluation kann nun direkt mehrere Adhoc Questions enthalten, dazu muss aber der adhocQuestion 
   Bool-Wert auf true gesetzt werden.
4. TextquestionFirst wird nicht mehr genutzt, bleibt aber erhalten um die Abwärtskompatibilität sicher zu stellen, stattdessen ist er nun möglich in Question einen rank festzulegen, welcher bestimmt, an welcher Position die Frage gestellt wird. Momentan ist noch nicht entschieden, ob oder wie doppelte ranks abgefangen werden.
5. Question hat zu QuestionRevision eine n zu 1 Beziehung. Dies soll verhindern, Das Fragen in alten Fragebögen irrtümlich rückwirkend geändert werden.
