### ISSUE TITLE
> 99 students lead to error page

### ISSUE THREAD

**Issue by ketain** [TH-Brandenburg/University-Evaluation-Backend#11]
creating a evaluation that generates qr codes for more than 99 students leads to this error page:
![pastedgraphic-3](https://cloud.githubusercontent.com/assets/9215393/16205846/076939b6-3726-11e6-98f1-6a1c52d1fbee.png)

**Comment by toni-anders** [comment]
How many students a evaluation have to has? Minimun two or three?
