### ISSUE TITLE
XML-File after parsing a DSL-Text file

### ISSUE THREAD

**Issue by AlexanderBond** [TH-Brandenburg/University-Evaluation-Backend#13]
[parser-xml.zip](https://github.com/TH-Brandenburg/University-Evaluation-Backend/files/364137/parser-xml.zip)

**Comment by toni-anders** [comment]
-Bitte erklärt eure XML Datei genauer. Z.B. wie soll man die SC-Fragen unterscheiden (best in the middle,  best to worse); 
- Dann solltet Ihr darauf achten das bei b.i.t.m. die Grade stimmen (3,2,1,-2,-3 bei 5 Antworten)
- Was bedeutet das Attribut: "line"?
- Was bedeutet das Attribut: "error"?
- Was ist mit der K.A.-Antwort?
- als Type würde sich (SingleChoice(SC) und SC-best in the middle (SCBM) und Text) anbieten

**Comment by AlexanderBond** [comment]
Attribut "error" enthält den Text der Fehlermeldung
"Line" ist die Nummer der Zeile
