### ISSUE TITLE
Provide superusers with more insight

### ISSUE THREAD

**Issue by ketain** [TH-Brandenburg/University-Evaluation-Backend#5]
Develop additional views only superusers have access to. Those views should display or genrate information regarding all evaluations of other (lesser :D) users. 

-> core team has to implement "superusers first".

**Comment by tobibrb** [comment]
Superuser is implemented. He needs to be declared manually in the DB's tutor table
example: 

`INSERT INTO tutor (id, username, department, family_name, name, is_superuser) VALUES
  (30, 'bartz', 0, 'Bartz', 'Tobias', TRUE);`

Use the TutorService isSuperuser(String username) method to check whether the user is superuser or not. For now only available in ldap branch.
